name: 'Hello World'
description: 'Greet someone'
inputs:
  webhook-url:
    description: 'Webhook URL to send the JSON payload'
    required: true
runs:
  using: "composite"
  steps:
    - name: Send JSON Payload to Teams
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d @post.json \
             ${{ secrets.TEAMS_WEBHOOK_URL }}
      shell: bash