name: 'Send Notification to Teams'
description: 'Send Notification to Teams'
inputs:
  webhook-url:
    description: 'Webhook URL to send the JSON payload'
    required: true
runs:
  using: "composite"
  steps:
    - name: Send JSON Payload to Teams
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d @post.json \
             ${{ inputs.webhook-url }}
      shell: bash