name: 'Send Notifications to Teams'
description: 'Send Start and End Notifications to Teams'
inputs:
  webhook-url:
    description: 'Webhook URL to send the JSON payload'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get run details
      id: run_details
      run: |
        run_data=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }})
        echo "run_data=$run_data" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Send Start Notification to Teams
      env:
        RUN_DATA: ${{ steps.run_details.outputs.run_data }}
      run: |
        # Extract data from RUN_DATA
        workflow_name=$(echo "$RUN_DATA" | jq -r '.name')
        run_number=$(echo "$RUN_DATA" | jq -r '.run_number')
        event=$(echo "$RUN_DATA" | jq -r '.event')
        actor=$(echo "$RUN_DATA" | jq -r '.actor.login')
        head_commit_message=$(echo "$RUN_DATA" | jq -r '.head_commit.message')
        head_commit_author=$(echo "$RUN_DATA" | jq -r '.head_commit.author.name')

        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "0076D7",
          "summary": "GitHub Action Started",
          "sections": [{
              "activityTitle": "GitHub Action Started: '"$workflow_name"'",
              "activitySubtitle": "Repository: '"${{ github.repository }}"'",
              "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "facts": [{
                  "name": "Run Number",
                  "value": "'"$run_number"'"
              }, {
                  "name": "Event",
                  "value": "'"$event"'"
              }, {
                  "name": "Actor",
                  "value": "'"$actor"'"
              }, {
                  "name": "Commit Message",
                  "value": "'"$head_commit_message"'"
              }, {
                  "name": "Commit Author",
                  "value": "'"$head_commit_author"'"
              }],
              "markdown": true
          }],
          "potentialAction": [{
              "@type": "OpenUri",
              "name": "View Run",
              "targets": [{
                  "os": "default",
                  "uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }]
          }]
        }' \
             ${{ inputs.webhook-url }}
      shell: bash

    - name: Run your job steps here
      run: |
        # Your job steps go here
        echo "Running job steps..."
      shell: bash

    - name: Send End Notification to Teams
      env:
        RUN_DATA: ${{ steps.run_details.outputs.run_data }}
      run: |
        # Get updated run data
        updated_run_data=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }})
        
        # Extract data from updated_run_data
        workflow_name=$(echo "$updated_run_data" | jq -r '.name')
        run_number=$(echo "$updated_run_data" | jq -r '.run_number')
        status=$(echo "$updated_run_data" | jq -r '.status')
        conclusion=$(echo "$updated_run_data" | jq -r '.conclusion')
        updated_at=$(echo "$updated_run_data" | jq -r '.updated_at')

        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "0076D7",
          "summary": "GitHub Action Completed",
          "sections": [{
              "activityTitle": "GitHub Action Completed: '"$workflow_name"'",
              "activitySubtitle": "Repository: '"${{ github.repository }}"'",
              "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "facts": [{
                  "name": "Run Number",
                  "value": "'"$run_number"'"
              }, {
                  "name": "Status",
                  "value": "'"$status"'"
              }, {
                  "name": "Conclusion",
                  "value": "'"$conclusion"'"
              }, {
                  "name": "Completed At",
                  "value": "'"$updated_at"'"
              }],
              "markdown": true
          }],
          "potentialAction": [{
              "@type": "OpenUri",
              "name": "View Run",
              "targets": [{
                  "os": "default",
                  "uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }]
          }]
        }' \
             ${{ inputs.webhook-url }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
