name: 'Send Notification to Teams'
description: 'Send Notification to Teams with Pre and Post Run'
inputs:
  webhook-url:
    description: 'Webhook URL to send the JSON payload'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Pre-run Notification
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "0076D7",
          "summary": "GitHub Action Pre-Run Notification",
          "sections": [{
              "activityTitle": "GitHub Action Started: ${{ github.workflow }}",
              "activitySubtitle": "Repository: ${{ github.repository }}",
              "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "facts": [{
                  "name": "Run Number",
                  "value": "${{ github.run_number }}"
              }, {
                  "name": "Event",
                  "value": "${{ github.event_name }}"
              }, {
                  "name": "Actor",
                  "value": "${{ github.actor }}"
              }],
              "markdown": true
          }],
          "potentialAction": [{
              "@type": "OpenUri",
              "name": "View Run",
              "targets": [{
                  "os": "default",
                  "uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }]
          }]
        }' \
             ${{ inputs.webhook-url }}
      shell: bash

    - name: Get run details
      id: run_details
      run: |
        run_data=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }})
        echo "run_data=$run_data" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Send Post-Run JSON Payload to Teams
      env:
        RUN_DATA: ${{ steps.run_details.outputs.run_data }}
      run: |
        # Extract data from RUN_DATA
        workflow_name=$(echo "$RUN_DATA" | jq -r '.name')
        run_number=$(echo "$RUN_DATA" | jq -r '.run_number')
        event=$(echo "$RUN_DATA" | jq -r '.event')
        status=$(echo "$RUN_DATA" | jq -r '.status')
        conclusion=$(echo "$RUN_DATA" | jq -r '.conclusion')
        created_at=$(echo "$RUN_DATA" | jq -r '.created_at')
        updated_at=$(echo "$RUN_DATA" | jq -r '.updated_at')
        actor=$(echo "$RUN_DATA" | jq -r '.actor.login')
        head_commit_message=$(echo "$RUN_DATA" | jq -r '.head_commit.message')
        head_commit_author=$(echo "$RUN_DATA" | jq -r '.head_commit.author.name')
        head_commit_timestamp=$(echo "$RUN_DATA" | jq -r '.head_commit.timestamp')

        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "0076D7",
          "summary": "GitHub Action Post-Run Notification",
          "sections": [{
              "activityTitle": "GitHub Action Completed: '"$workflow_name"'",
              "activitySubtitle": "Repository: '"${{ github.repository }}"'",
              "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "facts": [{
                  "name": "Run Number",
                  "value": "'"$run_number"'"
              }, {
                  "name": "Event",
                  "value": "'"$event"'"
              }, {
                  "name": "Status",
                  "value": "'"$status"'"
              }, {
                  "name": "Conclusion",
                  "value": "'"$conclusion"'"
              }, {
                  "name": "Created At",
                  "value": "'"$created_at"'"
              }, {
                  "name": "Updated At",
                  "value": "'"$updated_at"'"
              }, {
                  "name": "Actor",
                  "value": "'"$actor"'"
              }, {
                  "name": "Commit Message",
                  "value": "'"$head_commit_message"'"
              }, {
                  "name": "Commit Author",
                  "value": "'"$head_commit_author"'"
              }, {
                  "name": "Commit Timestamp",
                  "value": "'"$head_commit_timestamp"'"
              }],
              "markdown": true
          }],
          "potentialAction": [{
              "@type": "OpenUri",
              "name": "View Run",
              "targets": [{
                  "os": "default",
                  "uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }]
          }]
        }' \
             ${{ inputs.webhook-url }}
      shell: bash
