name: Test Action

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  send_notification_to_teams:
    runs-on: ubuntu-latest
    name: Send Notification to Teams
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Notification to Teams
        uses: ./action.yml
        with:
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}