on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Notification to Teams
        uses: satyatulasijalandharch/Teams-Notification@v1.0.1
        with:
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}