name: Test Action

on:
  push:
    branches:
      - main

jobs:
  send_notification_to_teams:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    name: Send Notification to Teams
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Notification to Teams
        uses: ./.github/actions/ms-notify
        with:
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          github-token: ${{ github.token }}
