name: Test Action

on:
  push:
    branches:
      - main

jobs:
  notify-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send Notifications
        uses: ./.github/actions/ms-notify
        with:
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}