on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      # Grant permissions to the script in the action
      - name: Set executable permission for goodbye.sh
        run: |
          ls -a
          chmod +x ./_actions/satyatulasijalandharch/Teams-Notification/v1/goodbye.sh

      - id: foo
        uses: satyatulasijalandharch/Teams-Notification@v1
        with:
          who-to-greet: 'Mona the Octocat'

      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
